version: '3.3'
services:
  ldes-server:
    env_file:
      - ./config.local.env
    container_name: ldes-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${LDES_PORT}:8080"
    networks:
      - ldes

networks:
  ldes:
    driver: bridge
    